Update deb.yml
fixed indentation

diff --git a/.github/workflows/deb.yml b/.github/workflows/deb.yml
--- a/.github/workflows/deb.yml
+++ b/.github/workflows/deb.yml
@@ -34,52 +34,51 @@ jobs:
       # Build your program with the given configuration
       run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
 
-    -name: Install to DEB
-    run: |
-      pkgdir=".debpkg"
-      mkdir -p ${pkgdir}/usr/bin
-      mkdir -p ${pkgdir}/DEBIAN
-      make DESTDIR=".debpkg/" install || echo "'make install' failed" ; return 1
-      for _size in 16 24 32 48 64 96 128 256 512; do
-        install -Dm644 "${{github.workspace}}/resources/icons/hicolor/${_size}x${_size}.png" "$pkgdir/usr/share/icons/hicolor/${_size}x${_size}/apps/harvest.png"
-      done
+    - name: Install to DEB
+      run: |
+        mkdir -p .debpkg/usr/bin
+        mkdir -p .debpkg/DEBIAN
+        make DESTDIR=".debpkg/" install || echo "'make install' failed" ; return 1
+        for _size in 16 24 32 48 64 96 128 256 512; do
+          install -Dm644 "${{github.workspace}}/resources/icons/hicolor/${_size}x${_size}.png" ".debpkg/usr/share/icons/hicolor/${_size}x${_size}/apps/harvest.png"
+        done
 
-      install -Dm644 "${{github.workspace}}/resources/desktop/harvest.svg" "${pkgdir}/usr/share/icons/hicolor/scalable/apps/harvest.svg"
+        install -Dm644 "${{github.workspace}}/resources/desktop/harvest.svg" ".debpkg/usr/share/icons/hicolor/scalable/apps/harvest.svg"
 
-	    install -Dm755 "${{github.workspace}}/resources/desktop/harvest.desktop" "${pkgdir}/usr/share/applications/harvest.desktop"
+        install -Dm755 "${{github.workspace}}/resources/desktop/harvest.desktop" ".debpkg/usr/share/applications/harvest.desktop"
 
-    -name: Add copyright
-    run: |
-      echo 'Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/                                                                                                                                                                                                                                                                                                ✔ 
-Upstream-Name: harvesttimer-qt
-Upstream-Contact: Jorge Barroso <jorge_barroso_11@hotmail.com>
-Source: https://github.com/jorge-barroso/harvesttimer-qt
+    - name: Add copyright
+      run: |
+        echo 'Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/ 
+              Upstream-Name: harvesttimer-qt
+              Upstream-Contact: Jorge Barroso <jorge_barroso_11@hotmail.com>
+              Source: https://github.com/jorge-barroso/harvesttimer-qt
+              
+              Files: *
+              Copyright: 2022 Jorge Barroso <jorge_barroso_11@hotmail.com>
+              
+              License: GPL-3.0+
+              
+              Files: debian/*
+              Copyright: 2022 Jorge Barroso <jorge_barroso_11@hotmail.com>
+              License: GPL-3.0+
 
-Files: *
-Copyright: 2022 Jorge Barroso <jorge_barroso_11@hotmail.com>
-
-License: GPL-3.0+
-
-Files: debian/*
-Copyright: 2022 Jorge Barroso <jorge_barroso_11@hotmail.com>
-License: GPL-3.0+
-
-License: GPL-3.0+
- This program is free software: you can redistribute it and/or modify
- it under the terms of the GNU General Public License as published by
- the Free Software Foundation, either version 3 of the License, or
- (at your option) any later version.
- .
- This package is distributed in the hope that it will be useful,
- but WITHOUT ANY WARRANTY; without even the implied warranty of
- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
- GNU General Public License for more details.
- .
- You should have received a copy of the GNU General Public License
- along with this program. If not, see <https://www.gnu.org/licenses/>.
- .
- On Debian systems, the complete text of the GNU General
- Public License version 3 can be found in "/usr/share/common-licenses/GPL-3".' > .debpkg/DEBIAN/copyright
+              License: GPL-3.0+
+               This program is free software: you can redistribute it and/or modify
+               it under the terms of the GNU General Public License as published by
+               the Free Software Foundation, either version 3 of the License, or
+               (at your option) any later version.
+               .
+               This package is distributed in the hope that it will be useful,
+               but WITHOUT ANY WARRANTY; without even the implied warranty of
+               MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+               GNU General Public License for more details.
+               .
+               You should have received a copy of the GNU General Public License
+               along with this program. If not, see <https://www.gnu.org/licenses/>.
+               .
+               On Debian systems, the complete text of the GNU General
+               Public License version 3 can be found in "/usr/share/common-licenses/GPL-3".' > .debpkg/DEBIAN/copyright
     - uses: jiro4989/build-deb-action@v2
       with:
         package: harvesttimer-qt
